/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/catppuccin-matcha.ts
 * Command: astryx theme build src/themes/catppuccin-matcha.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const catppuccinMatchaTheme: DefinedTheme;
